# Generated by Django 4.2.2 on 2023-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
                ('opciones', models.CharField(choices=[('Compra', 'Compra'), ('Vende', 'Vende')], max_length=10)),
                ('propiedad', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacto_preferido', models.CharField(choices=[('telefono', 'Teléfono'), ('email', 'E-mail')], max_length=10)),
                ('fecha_contacto', models.DateField(blank=True, null=True)),
                ('hora_contacto', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
